## **Week 1 — Data Acquisition, Cleaning and Preprocessing**

### Project
E-Commerce Customer Analytics, Segmentation & Predictive Modeling

## Dataset
UCI Online Retail II

In [10]:
import pandas as pd  # load dataset

In [7]:
df = pd.read_excel("/content/online_retail_II.xlsx")

In [11]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.shape

(525461, 8)

In [9]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [13]:
pd.ExcelFile("/content/online_retail_II.xlsx").sheet_names   # Discovered the two sheets

['Year 2009-2010', 'Year 2010-2011']

In [18]:
df_2009_2010 = pd.read_excel(
    "/content/online_retail_II.xlsx",
    sheet_name="Year 2009-2010"
)

df_2010_2011 = pd.read_excel(
    "/content/online_retail_II.xlsx",
    sheet_name="Year 2010-2011"
)

print("2009-2010:", df_2009_2010.shape)
print("2010-2011:", df_2010_2011.shape)    # Combined both sheets

2009-2010: (525461, 8)
2010-2011: (541910, 8)

In [20]:
df = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

df.shape                                # Confirmed final dataset = 1,067,371 × 8

(1067371, 8)

In [22]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [23]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [30]:
summary_stats = df.describe()

print(summary_stats.to_string())

           Quantity                    InvoiceDate         Price    Customer ID
count  1.067371e+06                        1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394028544  4.649388e+00   15324.638504
min   -8.099500e+04            2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00            2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00            2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01            2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04            2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                            NaN  1.235531e+02    1697.464450

In [31]:
numeric_summary = df[
    ["Quantity", "Price", "Customer ID"]
].describe()

print(numeric_summary.to_string())

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [26]:
df.isnull().sum()              #Checked missing values

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [27]:
df.duplicated().sum()         #Checked duplicate rows

np.int64(34335)

DATA QUALITY ASSESMENT

In [32]:
negative_quantity_count = (df["Quantity"] < 0).sum()

print("Number of transactions with negative quantity:",
      negative_quantity_count)

Number of transactions with negative quantity: 22950

In [33]:
negative_quantity_rows = df[df["Quantity"] < 0]

negative_quantity_rows.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [34]:
negative_with_cancellation_invoice = (
    negative_quantity_rows["Invoice"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

print(
    "Negative-quantity transactions with cancellation invoices:",
    negative_with_cancellation_invoice
)

Negative-quantity transactions with cancellation invoices: 19493

In [35]:
negative_without_cancellation = negative_quantity_rows[
    ~negative_quantity_rows["Invoice"]
    .astype(str)
    .str.startswith("C")
]

print(
    "Negative-quantity transactions without cancellation invoice:",
    len(negative_without_cancellation)
)

Negative-quantity transactions without cancellation invoice: 3457

In [36]:
negative_without_cancellation["Invoice"].astype(str).str[:1].value_counts()

Invoice
5    2728
4     729
Name: count, dtype: int64

In [37]:
# 1. Count zero-quantity transactions
zero_quantity_count = (df["Quantity"] == 0).sum()

print("Number of transactions with zero quantity:",
      zero_quantity_count)


# 2. Extract zero-quantity transactions
zero_quantity_rows = df[df["Quantity"] == 0]

print("\nSample zero-quantity transactions:")
display(zero_quantity_rows.head(10))


# 3. Examine invoice-number patterns
invoice_patterns = (
    zero_quantity_rows["Invoice"]
    .astype(str)
    .str[:1]
    .value_counts()
)

print("\nInvoice-number patterns among zero-quantity transactions:")
print(invoice_patterns)

Number of transactions with zero quantity: 0

Sample zero-quantity transactions:

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

Invoice-number patterns among zero-quantity transactions:
Series([], Name: count, dtype: int64)

In [38]:
# 1. Count negative-price transactions
negative_price_count = (df["Price"] < 0).sum()

print("Number of transactions with negative price:",
      negative_price_count)


# 2. Extract negative-price transactions
negative_price_rows = df[df["Price"] < 0]

print("\nSample negative-price transactions:")
display(negative_price_rows.head(10))


# 3. Examine invoice-number patterns
invoice_patterns = (
    negative_price_rows["Invoice"]
    .astype(str)
    .str[:1]
    .value_counts()
)

print("\nInvoice-number patterns among negative-price transactions:")
print(invoice_patterns)

Number of transactions with negative price: 5

Sample negative-price transactions:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

Invoice-number patterns among negative-price transactions:
Invoice
A    5
Name: count, dtype: int64

In [39]:

zero_price = df[df["Price"] == 0]

print("Zero-price transactions:", len(zero_price))
display(zero_price.head(10))

Zero-price transactions: 6202

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [40]:

missing_customer = df[df["Customer ID"].isna()]

print("Missing Customer ID:", len(missing_customer))
print("Percentage of dataset:",
      round(len(missing_customer) / len(df) * 100, 2), "%")

display(missing_customer.head(10))

Missing Customer ID: 243007
Percentage of dataset: 22.77 %

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom

In [41]:
missing_description = df[df["Description"].isna()]

print("Missing Description:", len(missing_description))
print("Percentage of dataset:",
      round(len(missing_description) / len(df) * 100, 2), "%")

display(missing_description.head(10))

Missing Description: 4382
Percentage of dataset: 0.41 %

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom

In [42]:
duplicate_count = df.duplicated().sum()

print("Completely duplicated records:", duplicate_count)
print("Percentage of dataset:",
      round(duplicate_count / len(df) * 100, 2), "%")

display(df[df.duplicated(keep=False)].head(10))

Completely duplicated records: 34335
Percentage of dataset: 3.22 %

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [43]:
for column in ["Quantity", "Price"]:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]

    print(f"\n{column}")
    print("Lower limit:", lower_limit)
    print("Upper limit:", upper_limit)
    print("Number of outliers:", len(outliers))

Quantity
Lower limit: -12.5
Upper limit: 23.5
Number of outliers: 116489

Price
Lower limit: -3.1000000000000005
Upper limit: 8.5
Number of outliers: 68105

## DATA CLEANING

In [44]:
# Create a copy of the raw dataset
df_clean = df.copy()

print("Original rows:", len(df_clean))

Original rows: 1067371

In [45]:
# Remove exact duplicate records
df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:", len(df_clean))

Rows after removing duplicates: 1033036

In [46]:
# Remove negative-price bad-debt adjustment records
df_clean = df_clean[df_clean["Price"] >= 0]

print("Rows after removing bad-debt records:", len(df_clean))

Rows after removing bad-debt records: 1033031

In [48]:
# Remove zero-price transactions
df_clean = df_clean[df_clean["Price"] > 0]

print("Rows after removing zero-price transactions:", len(df_clean))

Rows after removing zero-price transactions: 1027017

In [49]:
# Fill missing product descriptions
df_clean["Description"] = df_clean["Description"].fillna("Unknown")

print("Missing descriptions:", df_clean["Description"].isna().sum())

Missing descriptions: 0

In [50]:
# Flag cancelled transactions
df_clean["IsCancellation"] = df_clean["Invoice"].astype(str).str.startswith("C")

print("Cancellation transactions:",
      df_clean["IsCancellation"].sum())

Cancellation transactions: 19104

In [51]:
# Final cleaning validation
print("Rows:", len(df_clean))
print("Duplicates:", df_clean.duplicated().sum())
print("Negative prices:", (df_clean["Price"] < 0).sum())
print("Zero prices:", (df_clean["Price"] == 0).sum())
print("Missing descriptions:", df_clean["Description"].isna().sum())

Rows: 1027017
Duplicates: 0
Negative prices: 0
Zero prices: 0
Missing descriptions: 0

## PREPROCESSING

In [52]:
# Calculate total transaction value
df_clean["TotalAmount"] = df_clean["Quantity"] * df_clean["Price"]

df_clean[["Quantity", "Price", "TotalAmount"]].head()

   Quantity  Price  TotalAmount
0        12   6.95         83.4
1        12   6.75         81.0
2        12   6.75         81.0
3        48   2.10        100.8
4        24   1.25         30.0

In [53]:
# Create date-based features
df_clean["Year"] = df_clean["InvoiceDate"].dt.year
df_clean["Month"] = df_clean["InvoiceDate"].dt.month
df_clean["Day"] = df_clean["InvoiceDate"].dt.day

df_clean[["InvoiceDate", "Year", "Month", "Day"]].head()

          InvoiceDate  Year  Month  Day
0 2009-12-01 07:45:00  2009     12    1
1 2009-12-01 07:45:00  2009     12    1
2 2009-12-01 07:45:00  2009     12    1
3 2009-12-01 07:45:00  2009     12    1
4 2009-12-01 07:45:00  2009     12    1

In [54]:
# Check final dataset structure
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("\nMissing values:")
print(df_clean.isnull().sum())

Rows: 1027017
Columns: 13

Missing values:
Invoice                0
StockCode              0
Description            0
Quantity               0
InvoiceDate            0
Price                  0
Customer ID       229202
Country                0
IsCancellation         0
TotalAmount            0
Year                   0
Month                  0
Day                    0
dtype: int64

In [55]:
# Save cleaned dataset
df_clean.to_csv("/content/online_retail_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.